services:
  - type: web
    name: job-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0

